version: "2"
services:
  flexget:
    image: javi98/flexget
    container_name: flexget
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=12345678
    volumes:
      - ./flexget:/config
      - ./transmission/config/torrents:/home/flexget/torrents
      - ./transmission/downloads/complete:/downloads
    links:
      - transmission
    restart: always
